apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpfoyer-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: tpfoyer
  template:
    metadata:
      labels:
        app: tpfoyer
    spec:
      containers:
        - name: tpfoyer
          image: saifdenden/tpdevopssaifden:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/tpprojet2025?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root

